name: env_lisflood
channels:
  - conda-forge
dependencies:
  - jupyter_contrib_nbextensions
  - altair
  - cartopy
  - matplotlib
  - pcraster
  - pip
  - pip:
    - ipyfilechooser
    - lisflood-model
