name: lf_usecase
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - pcraster
  - gdal
  - altair
  - cartopy
  - ipyleaflet
  - ipyfilechooser
  - ipympl
  - jupyter_contrib_nbextensions
  - jupyterlab
  - jupyter-book
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - xarray
  - pip:
    - lisflood-model