name: lisflood
channels:
  - conda-forge
  - default
dependencies:
  - pcraster
  - jupyter_contrib_nbextensions
  - ipyleaflet
  - altair
  - cartopy
  - matplotlib
  - ipyfilechooser
  - ipympl
  - pip
  - pip:
    - lisflood-model
